---
title: "Example: Harness GitOps Entity Relationships"
---
erDiagram
    GITOPS-AGENT ||--o{ GITOPS-CLUSTER : "runs commands in"
    GITOPS-CLUSTER }o--o| ENVIRONMENT : "is compute infrastructure for"
    SERVICE |o--o{ APPLICATION : "represenents deployed workload of"
    ENVIRONMENT }o--o{ APPLICATION : "is deployment target for"
    REPOSITORY |o--o{ SERVICE : "contains deployment manifests for"
    REPOSITORY ||--o{ APPLICATION: "hosts declarative state of"
