service:
  name: podinfo
  identifier: podinfo
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: configjson
            type: ReleaseRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: githubconnector
                  gitFetchType: Branch
                  paths:
                    - configs/git-generator-files-discovery/cluster-config/engineering/<+env.name>/config.json
                  branch: main
        - manifest:
            identifier: podinfodeploy
            type: DeploymentRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: githubconnector
                  gitFetchType: Branch
                  paths:
                    - configs/git-generator-files-discovery/apps/podinfo/deployment.yaml
                  branch: main
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: docker_connector
                imagePath: nicholaslotz/harness-gitops-workshop
                tag: <+trigger.commitSha>
                digest: ""
              identifier: podinfoartifact
              type: DockerRegistry
    type: Kubernetes
  gitOpsEnabled: true
